# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        # The first requirements are for pygobject.
        # The last - xvfb - comes from https://pygobject.readthedocs.io/en/latest/guide/testing.html:
        # to run a GTK app headless we create a fake X server with xvfb
        sudo apt-get update &&\
        sudo apt-get install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config gir1.2-gtk-3.0 xvfb &&\
        pip install -r .github/workflows/requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        xvfb-run pytest unit/
